-- Master Inventory Seed Data
-- Generated from Walmart + HEB + Amazon purchase history
-- Family of 8, Boerne TX, April 2026

-- Create inventory tables if not exist

CREATE TABLE IF NOT EXISTS inventory_items (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  canonical_name TEXT NOT NULL,
  category TEXT NOT NULL,        -- App category: Fridge, Freezer, Pantry, etc.
  sub_category TEXT NOT NULL,    -- Sub-category within the main category
  preferred_store TEXT,          -- Walmart, HEB, or Amazon
  available_stores TEXT[],       -- Array of stores that carry this item
  par_level INT DEFAULT 1,       -- How many to keep on hand
  par_unit TEXT DEFAULT 'item',  -- Unit for par level
  reorder_threshold INT DEFAULT 0, -- Reorder when stock drops to this
  current_stock INT DEFAULT 0,   -- Current quantity on hand
  location TEXT,                 -- Where stored: main_fridge, deep_freezer, pantry_shelf_1, etc.
  last_purchased TIMESTAMPTZ,
  avg_price DECIMAL(8,2),
  notes TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory_items(category);
CREATE INDEX IF NOT EXISTS idx_inventory_sub_category ON inventory_items(sub_category);
CREATE INDEX IF NOT EXISTS idx_inventory_name ON inventory_items(canonical_name);


-- Seed inventory items
INSERT INTO inventory_items (name, canonical_name, category, sub_category, preferred_store, available_stores, par_level, par_unit, reorder_threshold) VALUES
  ('Active Dry Yeast', 'active dry yeast', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('All-Purpose Flour', 'all-purpose flour', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Baking Soda', 'baking soda', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Betty Crocker Rich & Creamy Chocolate Frosting', 'betty crocker rich & creamy chocolate frosting', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Betty Crocker Rich & Creamy Vanilla Frosting', 'betty crocker rich & creamy vanilla frosting', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Betty Crocker Super Moist Chocolate Fudge Cake Mix', 'betty crocker super moist chocolate fudge cake mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Betty Crocker Super Moist Yellow Cake Mix', 'betty crocker super moist yellow cake mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Coconut Milk', 'coconut milk', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Cornstarch', 'cornstarch', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Double Acting Baking Powder', 'double acting baking powder', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Duncan Hines Perfectly Moist Classic Yellow Cake Mix', 'duncan hines perfectly moist classic yellow cake mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Evaporated Milk', 'evaporated milk', 'Baking Cabinet', 'Baking Essentials', 'HEB', ARRAY['HEB','Walmart'], 2, 'per type', 0),
  ('Fleischmann''s Active Dry Yeast', 'fleischmann''s active dry yeast', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Graham Crackers', 'graham crackers', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Hershey''s Cocoa Natural Unsweetened', 'hershey''s cocoa natural unsweetened', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Jell-O Chocolate Instant Pudding Mix', 'jell-o chocolate instant pudding mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Jell-O Strawberry Gelatin Dessert Mix', 'jell-o strawberry gelatin dessert mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Jell-O Vanilla Instant Pudding Mix', 'jell-o vanilla instant pudding mix', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Jet-Puffed Marshmallows', 'jet-puffed marshmallows', 'Baking Cabinet', 'Baking Essentials', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Jet-Puffed Mini Marshmallows', 'jet-puffed mini marshmallows', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Karo Light Corn Syrup', 'karo light corn syrup', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Keebler Ready Crust Pie Crust, 9 inch', 'keebler ready crust pie crust, 9 inch', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Knox Unflavored Gelatin', 'knox unflavored gelatin', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Light Brown Sugar', 'light brown sugar', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Light Corn Syrup', 'light corn syrup', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Mini Marshmallows', 'mini marshmallows', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Mrs. Butterworth''s Original Thick and Rich Pancake Syrup', 'mrs. butterworth''s original thick and rich pancake syrup', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Nestlé Carnation Evaporated Milk', 'nestlé carnation evaporated milk', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Powdered Sugar', 'powdered sugar', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Pure Granulated Sugar', 'pure granulated sugar', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Pure Maple Syrup', 'pure maple syrup', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Pure Vanilla Extract', 'pure vanilla extract', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Semi-Sweet Chocolate Chips', 'semi-sweet chocolate chips', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Sweetened Coconut Flakes', 'sweetened coconut flakes', 'Baking Cabinet', 'Baking Essentials', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Sweetened Condensed Milk', 'sweetened condensed milk', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Sweetened Shredded Coconut', 'sweetened shredded coconut', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Swiss Miss Marshmallows Hot Cocoa Drink Mix', 'swiss miss marshmallows hot cocoa drink mix', 'Baking Cabinet', 'Baking Essentials', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Unsweetened Cocoa Powder', 'unsweetened cocoa powder', 'Baking Cabinet', 'Baking Essentials', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Buttermilk Pancakes', 'buttermilk pancakes', 'Freezer', 'Frozen Breakfast', 'Walmart', ARRAY['Walmart'], 3, 'boxes', 1),
  ('Eggo Blueberry Frozen Waffles - Family Pack', 'eggo blueberry frozen waffles - family pack', 'Freezer', 'Frozen Breakfast', 'HEB', ARRAY['HEB'], 3, 'boxes', 1),
  ('Eggo Buttermilk Frozen Waffles - Family Pack', 'eggo buttermilk frozen waffles - family pack', 'Freezer', 'Frozen Breakfast', 'HEB', ARRAY['HEB'], 3, 'boxes', 1),
  ('Eggo Homestyle Frozen Waffles - Family Pack', 'eggo homestyle frozen waffles - family pack', 'Freezer', 'Frozen Breakfast', 'HEB', ARRAY['HEB'], 3, 'boxes', 1),
  ('Eggo Homestyle Waffles', 'eggo homestyle waffles', 'Freezer', 'Frozen Breakfast', 'Walmart', ARRAY['Walmart'], 3, 'boxes', 1),
  ('Frozen Waffles - Buttermilk, Family Pack', 'frozen waffles - buttermilk, family pack', 'Freezer', 'Frozen Breakfast', 'HEB', ARRAY['HEB'], 3, 'boxes', 1),
  ('Fully Cooked Frozen Kolaches - Sausage & Cheese', 'fully cooked frozen kolaches - sausage & cheese', 'Freezer', 'Frozen Breakfast', 'HEB', ARRAY['HEB'], 3, 'boxes', 1),
  ('Jimmy Dean Sausage, Egg & Cheese Croissant Sandwiches', 'jimmy dean sausage, egg & cheese croissant sandwiches', 'Freezer', 'Frozen Breakfast', 'Walmart', ARRAY['Walmart'], 3, 'boxes', 1),
  ('Sausage Egg & Cheese Biscuit Sandwiches', 'sausage egg & cheese biscuit sandwiches', 'Freezer', 'Frozen Breakfast', 'Walmart', ARRAY['Walmart'], 3, 'boxes', 1),
  ('Waffle Fries', 'waffle fries', 'Freezer', 'Frozen Breakfast', 'Walmart', ARRAY['Walmart'], 3, 'boxes', 1),
  ('Cool Whip Original Whipped Topping', 'cool whip original whipped topping', 'Freezer', 'Frozen Desserts', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Frozen Whipped Topping', 'frozen whipped topping', 'Freezer', 'Frozen Desserts', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Marie Callender''s Dutch Apple Pie', 'marie callender''s dutch apple pie', 'Freezer', 'Frozen Desserts', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Dole Frozen Mixed Fruit', 'dole frozen mixed fruit', 'Freezer', 'Frozen Fruit', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Frozen Blueberries', 'frozen blueberries', 'Freezer', 'Frozen Fruit', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Frozen Mango Chunks', 'frozen mango chunks', 'Freezer', 'Frozen Fruit', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Frozen Strawberries', 'frozen strawberries', 'Freezer', 'Frozen Fruit', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Banquet Basic Salisbury Steak Meal', 'banquet basic salisbury steak meal', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Banquet Mega Bowls Country Fried Chicken', 'banquet mega bowls country fried chicken', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('DiGiorno Rising Crust Pepperoni Frozen Pizza', 'digiorno rising crust pepperoni frozen pizza', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('El Monterey Beef & Bean Chimichangas', 'el monterey beef & bean chimichangas', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('El Monterey Beef & Cheese Taquitos', 'el monterey beef & cheese taquitos', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Hot Pockets Ham & Cheese', 'hot pockets ham & cheese', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Hot Pockets Pepperoni Pizza', 'hot pockets pepperoni pizza', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('José Olé Beef & Cheese Mini Tacos', 'josé olé beef & cheese mini tacos', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Marie Callender''s Chicken Pot Pie', 'marie callender''s chicken pot pie', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Stouffer''s Family Size Lasagna with Meat & Sauce', 'stouffer''s family size lasagna with meat & sauce', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Thin Crust Pepperoni Pizza', 'thin crust pepperoni pizza', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Totino''s Party Pizza Combination', 'totino''s party pizza combination', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Totino''s Party Pizza Pepperoni', 'totino''s party pizza pepperoni', 'Freezer', 'Frozen Meals', 'Walmart', ARRAY['Walmart'], 4, 'meals', 2),
  ('Frozen Mozzarella Cheese Sticks', 'frozen mozzarella cheese sticks', 'Freezer', 'Frozen Other', 'HEB', ARRAY['HEB'], 2, 'items', 1),
  ('Boneless Skinless Chicken Breast', 'boneless skinless chicken breast', 'Freezer', 'Frozen Proteins', 'HEB', ARRAY['HEB'], 4, 'bags/packages', 2),
  ('Breaded Chicken Breast Nuggets', 'breaded chicken breast nuggets', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Breaded Chicken Breast Strips', 'breaded chicken breast strips', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Chicken Breast Tenderloins', 'chicken breast tenderloins', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Frozen Cooked Medium Peeled Shrimp', 'frozen cooked medium peeled shrimp', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Frozen Panko Breaded Butterfly Shrimp - Texas-Size Pack', 'frozen panko breaded butterfly shrimp - texas-size pack', 'Freezer', 'Frozen Proteins', 'HEB', ARRAY['HEB'], 4, 'bags/packages', 2),
  ('Frozen Raw Medium Shrimp', 'frozen raw medium shrimp', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Frozen Tilapia Skinless & Boneless Fillets', 'frozen tilapia skinless & boneless fillets', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Fully Cooked Frozen Beef & Pork Meatballs - Homestyle', 'fully cooked frozen beef & pork meatballs - homestyle', 'Freezer', 'Frozen Proteins', 'HEB', ARRAY['HEB'], 4, 'bags/packages', 2),
  ('Fully Cooked Frozen Original Beef Burgers', 'fully cooked frozen original beef burgers', 'Freezer', 'Frozen Proteins', 'HEB', ARRAY['HEB'], 4, 'bags/packages', 2),
  ('Gorton''s Beer Battered Fish Fillets', 'gorton''s beer battered fish fillets', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Natural Fully Cooked Frozen Southern Style Breaded Chicken Strips', 'natural fully cooked frozen southern style breaded chicken strips', 'Freezer', 'Frozen Proteins', 'HEB', ARRAY['HEB'], 4, 'bags/packages', 2),
  ('Tyson Frozen Boneless Skinless Chicken Breast', 'tyson frozen boneless skinless chicken breast', 'Freezer', 'Frozen Proteins', 'Walmart', ARRAY['Walmart'], 4, 'bags/packages', 2),
  ('Crinkle Cut French Fries', 'crinkle cut french fries', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Frozen Crinkle Cut French Fries', 'frozen crinkle cut french fries', 'Freezer', 'Frozen Sides', 'HEB', ARRAY['HEB'], 3, 'bags', 1),
  ('Frozen French Fries - Garlic & Herb', 'frozen french fries - garlic & herb', 'Freezer', 'Frozen Sides', 'HEB', ARRAY['HEB'], 3, 'bags', 1),
  ('Frozen French Fries - Seasoned', 'frozen french fries - seasoned', 'Freezer', 'Frozen Sides', 'HEB', ARRAY['HEB'], 3, 'bags', 1),
  ('Frozen French Fries - Slim-Cut Classic', 'frozen french fries - slim-cut classic', 'Freezer', 'Frozen Sides', 'HEB', ARRAY['HEB'], 3, 'bags', 1),
  ('Frozen Garlic Bread', 'frozen garlic bread', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Frozen Texas Toast - Garlic', 'frozen texas toast - garlic', 'Freezer', 'Frozen Sides', 'HEB', ARRAY['HEB'], 3, 'bags', 1),
  ('New York Bakery Five Cheese Texas Toast', 'new york bakery five cheese texas toast', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Ore-Ida Golden Fries French Fried Potatoes', 'ore-ida golden fries french fried potatoes', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Tater Tots', 'tater tots', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Texas Toast Garlic Bread', 'texas toast garlic bread', 'Freezer', 'Frozen Sides', 'Walmart', ARRAY['Walmart'], 3, 'bags', 1),
  ('Blue Bunny Mini Swirls Variety Pack', 'blue bunny mini swirls variety pack', 'Freezer', 'Frozen Treats', 'Walmart', ARRAY['Walmart'], 2, 'boxes', 1),
  ('Fudge Bars', 'fudge bars', 'Freezer', 'Frozen Treats', 'Walmart', ARRAY['Walmart'], 2, 'boxes', 1),
  ('Ice Cream Sandwiches', 'ice cream sandwiches', 'Freezer', 'Frozen Treats', 'Walmart', ARRAY['Walmart'], 2, 'boxes', 1),
  ('Popsicle Orange Cherry Grape Ice Pops', 'popsicle orange cherry grape ice pops', 'Freezer', 'Frozen Treats', 'Walmart', ARRAY['Walmart'], 2, 'boxes', 1),
  ('Birds Eye Steamfresh Mixed Vegetables', 'birds eye steamfresh mixed vegetables', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Frozen Broccoli Florets', 'frozen broccoli florets', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Frozen Cut Green Beans', 'frozen cut green beans', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Frozen Mixed Vegetables', 'frozen mixed vegetables', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Frozen Stir Fry Vegetables', 'frozen stir fry vegetables', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Frozen Sweet Corn', 'frozen sweet corn', 'Freezer', 'Frozen Vegetables', 'Walmart', ARRAY['Walmart'], 4, 'bags', 2),
  ('Modelo Especial Mexican Lager Import Beer', 'modelo especial mexican lager import beer', 'Fridge', 'Alcohol', 'Walmart', ARRAY['Walmart'], 1, 'pack', 0),
  ('Real Ale Hop Sprocket Hazy IPA Craft Beer', 'real ale hop sprocket hazy ipa craft beer', 'Fridge', 'Alcohol', 'Walmart', ARRAY['Walmart'], 1, 'pack', 0),
  ('Coffee mate Italian Sweet Crème Liquid Coffee Creamer', 'coffee mate italian sweet crème liquid coffee creamer', 'Fridge', 'Coffee Creamers', 'Walmart', ARRAY['Walmart'], 2, 'bottles', 1),
  ('International Delight Caramel Macchiato Cold Foam Coffee Creamer', 'international delight caramel macchiato cold foam coffee creamer', 'Fridge', 'Coffee Creamers', 'Walmart', ARRAY['Walmart'], 2, 'bottles', 1),
  ('International Delight Pumpkin Pie Spice Cold Foam Coffee Creamer', 'international delight pumpkin pie spice cold foam coffee creamer', 'Fridge', 'Coffee Creamers', 'Walmart', ARRAY['Walmart'], 2, 'bottles', 1),
  ('Italian Sweet Creme Coffee Creamer', 'italian sweet creme coffee creamer', 'Fridge', 'Coffee Creamers', 'Walmart', ARRAY['Walmart'], 2, 'bottles', 1),
  ('Land O''Lakes Unsalted Butter Sticks', 'land o''lakes unsalted butter sticks', 'Fridge', 'Dairy - Butter', 'Walmart', ARRAY['Walmart'], 2, 'boxes (4 sticks)', 1),
  ('Salted Butter Sticks', 'salted butter sticks', 'Fridge', 'Dairy - Butter', 'HEB', ARRAY['HEB','Walmart'], 3, 'boxes (4 sticks)', 1),
  ('Unsalted Butter Sticks', 'unsalted butter sticks', 'Fridge', 'Dairy - Butter', 'HEB', ARRAY['HEB','Walmart'], 3, 'boxes (4 sticks)', 1),
  ('Colby & Monterey Jack Cheese', 'colby & monterey jack cheese', 'Fridge', 'Dairy - Cheese', 'HEB', ARRAY['HEB'], 2, 'bags/blocks', 1),
  ('Finely Shredded Colby & Monterey Jack Cheese', 'finely shredded colby & monterey jack cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Finely Shredded Fiesta Blend Cheese', 'finely shredded fiesta blend cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Finely Shredded Mild Cheddar Cheese', 'finely shredded mild cheddar cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Finely Shredded Mozzarella Cheese', 'finely shredded mozzarella cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Grated Parmesan Cheese', 'grated parmesan cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Kraft Singles American Cheese Slices', 'kraft singles american cheese slices', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Low Moisture Part-Skim Mozzarella Cheese', 'low moisture part-skim mozzarella cheese', 'Fridge', 'Dairy - Cheese', 'HEB', ARRAY['HEB'], 2, 'bags/blocks', 1),
  ('Mild Cheddar Cheese Block', 'mild cheddar cheese block', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Muenster Cheese, Deli Sliced', 'muenster cheese, deli sliced', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Original Cottage Cheese', 'original cottage cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Pepper Jack Cheese Block', 'pepper jack cheese block', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Ricotta Cheese', 'ricotta cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Sharp Cheddar Cheese', 'sharp cheddar cheese', 'Fridge', 'Dairy - Cheese', 'HEB', ARRAY['HEB'], 2, 'bags/blocks', 1),
  ('Sharp Cheddar Cheese Block', 'sharp cheddar cheese block', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Shredded Parmesan Cheese', 'shredded parmesan cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('String Cheese', 'string cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('Velveeta Original Cheese', 'velveeta original cheese', 'Fridge', 'Dairy - Cheese', 'Walmart', ARRAY['Walmart'], 2, 'bags/blocks', 1),
  ('2% Reduced Fat Milk', '2% reduced fat milk', 'Fridge', 'Dairy - Milk & Cream', 'HEB', ARRAY['HEB'], 3, 'gallon', 1),
  ('2% Reduced Fat Milk, Gallon', '2% reduced fat milk, gallon', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('2% Reduced Fat Milk, Half Gallon', '2% reduced fat milk, half gallon', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Daisy Sour Cream', 'daisy sour cream', 'Fridge', 'Dairy - Milk & Cream', 'HEB', ARRAY['HEB','Walmart'], 4, 'gallon', 1),
  ('Half & Half', 'half & half', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Heavy Whipping Cream', 'heavy whipping cream', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Organics 2% Reduced Fat Milk, 1/', 'organics 2% reduced fat milk, 1/', 'Fridge', 'Dairy - Milk & Cream', 'HEB', ARRAY['HEB'], 3, 'gallon', 1),
  ('Original Cream Cheese', 'original cream cheese', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Philadelphia Original Cream Cheese', 'philadelphia original cream cheese', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Pillsbury Grands! Flaky Layers Buttermilk Biscuits', 'pillsbury grands! flaky layers buttermilk biscuits', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Refrigerated Biscuits Buttermilk', 'refrigerated biscuits buttermilk', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Sour Cream', 'sour cream', 'Fridge', 'Dairy - Milk & Cream', 'Walmart', ARRAY['Walmart'], 3, 'gallon', 1),
  ('Garlic & Herb Chicken Breast, Deli-Sliced', 'garlic & herb chicken breast, deli-sliced', 'Fridge', 'Dairy - Other', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Original Pepperoni Slices', 'original pepperoni slices', 'Fridge', 'Dairy - Other', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Pepperoni, Pre-Sliced', 'pepperoni, pre-sliced', 'Fridge', 'Dairy - Other', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Snack Pack Chocolate Pudding Cups Variety Family Pack', 'snack pack chocolate pudding cups variety family pack', 'Fridge', 'Dairy - Other', 'HEB', ARRAY['HEB'], 1, 'item', 0),
  ('14g Protein Nonfat Greek Yogurt - Vanilla', '14g protein nonfat greek yogurt - vanilla', 'Fridge', 'Dairy - Yogurt', 'HEB', ARRAY['HEB'], 2, 'packs', 1),
  ('Go-Gurt SpongeBob Strawberry and Cotton Candy Low Fat Yogurt', 'go-gurt spongebob strawberry and cotton candy low fat yogurt', 'Fridge', 'Dairy - Yogurt', 'Walmart', ARRAY['Walmart'], 2, 'packs', 1),
  ('Plain Greek Nonfat Yogurt', 'plain greek nonfat yogurt', 'Fridge', 'Dairy - Yogurt', 'Walmart', ARRAY['Walmart'], 2, 'packs', 1),
  ('Yoplait Original French Vanilla Low Fat Yogurt', 'yoplait original french vanilla low fat yogurt', 'Fridge', 'Dairy - Yogurt', 'Walmart', ARRAY['Walmart'], 2, 'packs', 1),
  ('Yoplait Original Strawberry Low Fat Yogurt', 'yoplait original strawberry low fat yogurt', 'Fridge', 'Dairy - Yogurt', 'Walmart', ARRAY['Walmart'], 2, 'packs', 1),
  ('Black Forest Ham, Pre-Sliced', 'black forest ham, pre-sliced', 'Fridge', 'Deli & Prepared', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Deli Cajun-Style Fried Turkey Breast, Custom Sliced, lb', 'deli cajun-style fried turkey breast, custom sliced, lb', 'Fridge', 'Deli & Prepared', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Deli Snack Pack - Roasted Red Pepper Hummus', 'deli snack pack - roasted red pepper hummus', 'Fridge', 'Deli & Prepared', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Deli Sundried Tomato Smoked Turkey Breast, Custom Sliced, lb', 'deli sundried tomato smoked turkey breast, custom sliced, lb', 'Fridge', 'Deli & Prepared', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Hard Salami, Pre-Sliced', 'hard salami, pre-sliced', 'Fridge', 'Deli & Prepared', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Honey Ham Pre-Sliced', 'honey ham pre-sliced', 'Fridge', 'Deli & Prepared', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Meal Simple by H-E-B Rotisserie Chicken - Lemon Pepper, Each', 'meal simple by h-e-b rotisserie chicken - lemon pepper, each', 'Fridge', 'Deli & Prepared', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Oven Roasted Turkey Breast, Pre-Sliced', 'oven roasted turkey breast, pre-sliced', 'Fridge', 'Deli & Prepared', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Sushiya California Sushi Roll Value Pack, 15 pc', 'sushiya california sushi roll value pack, 15 pc', 'Fridge', 'Deli & Prepared', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Cage Free Large Brown Eggs', 'cage free large brown eggs', 'Fridge', 'Eggs', 'Walmart', ARRAY['Walmart'], 3, 'dozen', 1),
  ('Freshness Guaranteed Hot & Ready Chicken Egg Roll', 'freshness guaranteed hot & ready chicken egg roll', 'Fridge', 'Eggs', 'Walmart', ARRAY['Walmart'], 3, 'dozen', 1),
  ('Large White Eggs', 'large white eggs', 'Fridge', 'Eggs', 'Walmart', ARRAY['Walmart'], 3, 'dozen', 1),
  ('Fresh Banana, Each', 'fresh banana, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Blackberries', 'fresh blackberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB','Walmart'], 6, 'items/bags', 2),
  ('Fresh Blueberries', 'fresh blueberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB','Walmart'], 6, 'items/bags', 2),
  ('Fresh Bunch of Bananas, 4-7 Bananas, Avg.', 'fresh bunch of bananas, 4-7 bananas, avg.', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Cantaloupe, Each', 'fresh cantaloupe, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Cosmic Crisp Apples', 'fresh cosmic crisp apples', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Extra Large Lemon, Each', 'fresh extra large lemon, each', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Gala Apples', 'fresh gala apples', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Granny Smith Apples', 'fresh granny smith apples', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB','Walmart'], 6, 'items/bags', 2),
  ('Fresh Hass Avocados', 'fresh hass avocados', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Hass Avocados, Each', 'fresh hass avocados, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Honeycrisp Apples', 'fresh honeycrisp apples', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Jumbo Blueberries', 'fresh jumbo blueberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Kiwi', 'fresh kiwi', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Kiwi Fruit, Each', 'fresh kiwi fruit, each', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Large Hass Avocado Bag, 3-', 'fresh large hass avocado bag, 3-', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Large Mango, Each', 'fresh large mango, each', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Lemons', 'fresh lemons', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Lime, Each', 'fresh lime, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Limes', 'fresh limes', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Mandarin Oranges', 'fresh mandarin oranges', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Mini Hass Avocados', 'fresh mini hass avocados', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Navel Oranges', 'fresh navel oranges', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Organic Raspberries', 'fresh organic raspberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Organic Strawberries', 'fresh organic strawberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Pineapple, Each', 'fresh pineapple, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Raspberries', 'fresh raspberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB','Walmart'], 6, 'items/bags', 2),
  ('Fresh Red Mango, Each', 'fresh red mango, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Red Seedless Grapes, Bag (', 'fresh red seedless grapes, bag (', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Seedless Lemons', 'fresh seedless lemons', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Seedless Watermelon, Each', 'fresh seedless watermelon, each', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Strawberries', 'fresh strawberries', 'Fridge', 'Fresh Fruit', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Premium Fresh Hydroponic Strawberries', 'premium fresh hydroponic strawberries', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Texas Roots Large Grapefruit, Avg.', 'texas roots large grapefruit, avg.', 'Fridge', 'Fresh Fruit', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('100% Pure Ground Beef Chuck, 80% Lean - Texas-Size Pack, Avg.', '100% pure ground beef chuck, 80% lean - texas-size pack, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('All Natural 73% Lean/27% Fat Ground Beef', 'all natural 73% lean/27% fat ground beef', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('All Natural 80% Lean/20% Fat Ground Beef Chuck', 'all natural 80% lean/20% fat ground beef chuck', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('All Natural 93% Lean/7% Fat Ground Turkey', 'all natural 93% lean/7% fat ground turkey', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('BBQ Seasoned Chicken Drumsticks, Avg.', 'bbq seasoned chicken drumsticks, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('BBQ Seasoned Chicken Leg Quarters - Texas-Size Pack, Avg.', 'bbq seasoned chicken leg quarters - texas-size pack, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('Ball Park Classic Franks', 'ball park classic franks', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Beef Chuck Roast, USDA Select, 2.0-', 'beef chuck roast, usda select, 2.0-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Beef Short Ribs, Bone-In, 1.5-', 'beef short ribs, bone-in, 1.5-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Beef Stew Meat, 1.0-', 'beef stew meat, 1.0-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Bone-In Chicken Thighs, 4.7-', 'bone-in chicken thighs, 4.7-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Bone-In Pork Chops Assorted, 2.5-', 'bone-in pork chops assorted, 2.5-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Boneless Beef New York Strip Steaks - USDA Select - Value Pack, Avg.', 'boneless beef new york strip steaks - usda select - value pack, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('Boneless Center Cut Pork Chops, 2.0-', 'boneless center cut pork chops, 2.0-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Boneless Center Loin Pork Chops - Value Pack, Avg.', 'boneless center loin pork chops - value pack, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('Boneless Skinless Chicken Breast, 4.7-', 'boneless skinless chicken breast, 4.7-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Boneless Skinless Chicken Thighs, 4.7-', 'boneless skinless chicken thighs, 4.7-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Butcher Bone-In Pork Shoulder Butt, 6.5-', 'butcher bone-in pork shoulder butt, 6.5-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Chicken Drumsticks', 'chicken drumsticks', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Eckrich Original Skinless Smoked Sausage', 'eckrich original skinless smoked sausage', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Hillshire Farm Smoked Sausage', 'hillshire farm smoked sausage', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Hot Dogs', 'hot dogs', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Jimmy Dean Premium Pork Regular Breakfast Sausage Roll', 'jimmy dean premium pork regular breakfast sausage roll', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Natural Boneless Chicken Breasts - Value Pack, Avg.', 'natural boneless chicken breasts - value pack, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('Original Bacon', 'original bacon', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Original Breakfast Sausage Patties', 'original breakfast sausage patties', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Oscar Mayer Original Fully Cooked Bacon', 'oscar mayer original fully cooked bacon', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Pork Spare Ribs, 3.0-', 'pork spare ribs, 3.0-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Seasoned Chicken Breast Fajitas, Avg.', 'seasoned chicken breast fajitas, avg.', 'Fridge', 'Fresh Meat', 'HEB', ARRAY['HEB'], 3, 'packages', 1),
  ('St. Louis Style Pork Ribs, 2.5-', 'st. louis style pork ribs, 2.5-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Whole Fryer Chicken, 5-', 'whole fryer chicken, 5-', 'Fridge', 'Fresh Meat', 'Walmart', ARRAY['Walmart'], 3, 'packages', 1),
  ('Fresh Atlantic Salmon Fillet Portion', 'fresh atlantic salmon fillet portion', 'Fridge', 'Fresh Seafood', 'Walmart', ARRAY['Walmart'], 1, 'package', 0),
  ('Fresh Large Shrimp, Shell On', 'fresh large shrimp, shell on', 'Fridge', 'Fresh Seafood', 'Walmart', ARRAY['Walmart'], 1, 'package', 0),
  ('Fresh Tilapia Fillet, 1.0-', 'fresh tilapia fillet, 1.0-', 'Fridge', 'Fresh Seafood', 'Walmart', ARRAY['Walmart'], 1, 'package', 0),
  ('Celery Snack Sticks', 'celery snack sticks', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Dole Classic Cole Slaw', 'dole classic cole slaw', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fieldpack Fresh Iceberg Lettuce', 'fieldpack fresh iceberg lettuce', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Asparagus & Seasoning Packet, Avg.', 'fresh asparagus & seasoning packet, avg.', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Baby Peeled Carrots', 'fresh baby peeled carrots', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Beefsteak Tomato, Each', 'fresh beefsteak tomato, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Beefsteak Tomatoes, Avg.', 'fresh beefsteak tomatoes, avg.', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Bell Pepper, Green, Each', 'fresh bell pepper, green, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Broccoli Crowns, Each', 'fresh broccoli crowns, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Brussels Sprouts', 'fresh brussels sprouts', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Carrot Sticks', 'fresh carrot sticks', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Celery Stalk, Each', 'fresh celery stalk, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Cilantro Bunch, Each', 'fresh cilantro bunch, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Cucumber, Each', 'fresh cucumber, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Garlic Bulb, Each', 'fresh garlic bulb, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Ginger Root, Each', 'fresh ginger root, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Gold Potatoes', 'fresh gold potatoes', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Green Bell Pepper, Each', 'fresh green bell pepper, each', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Green Cabbage, Each', 'fresh green cabbage, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Green Onions Bunch, Each', 'fresh green onions bunch, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Jalapeno Pepper, Each', 'fresh jalapeno pepper, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Red Potatoes', 'fresh red potatoes', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Roma Tomato, Avg.', 'fresh roma tomato, avg.', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Roma Tomato, Each', 'fresh roma tomato, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Romaine Lettuce Hearts', 'fresh romaine lettuce hearts', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Serrano Pepper, Each', 'fresh serrano pepper, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Spinach', 'fresh spinach', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Steamable French Green Beans', 'fresh steamable french green beans', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Sunrise Bell Peppers', 'fresh sunrise bell peppers', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Fresh Sweet Onions', 'fresh sweet onions', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Vine Ripe Tomatoes, Each', 'fresh vine ripe tomatoes, each', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh White Onions', 'fresh white onions', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Whole Russet Potatoes', 'fresh whole russet potatoes', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Fresh Yellow Onions', 'fresh yellow onions', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Season''s Select Fresh Roma Tomatoes', 'season''s select fresh roma tomatoes', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Shredded Fresh Iceberg Lettuce', 'shredded fresh iceberg lettuce', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Taylor Farms Caesar Chopped Salad Kit', 'taylor farms caesar chopped salad kit', 'Fridge', 'Fresh Vegetables', 'Walmart', ARRAY['Walmart'], 5, 'items/bags', 2),
  ('Texas Roots Fresh Red Onions', 'texas roots fresh red onions', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Texas Roots Fresh Russet Potatoes', 'texas roots fresh russet potatoes', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Texas Roots Fresh Sweet Onions', 'texas roots fresh sweet onions', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Vegetable Stir Fry Kit - Teriyaki', 'vegetable stir fry kit - teriyaki', 'Fridge', 'Fresh Vegetables', 'HEB', ARRAY['HEB'], 5, 'items/bags', 2),
  ('Pillsbury Crescent Rolls Original Refrigerated Canned Pastry Dough', 'pillsbury crescent rolls original refrigerated canned pastry dough', 'Fridge', 'Refrigerated Dough', 'Walmart', ARRAY['Walmart'], 2, 'cans', 1),
  ('Bounty Mega Roll Select-A-Size White Paper Towel', 'bounty mega roll select-a-size white paper towel', 'Household', 'Cleaning & Paper', 'HEB', ARRAY['HEB'], 2, 'per type', 1),
  ('Cascade Platinum Dishwasher Pods, Fresh', 'cascade platinum dishwasher pods, fresh', 'Household', 'Cleaning & Paper', 'Amazon', ARRAY['Amazon'], 2, 'per type', 1),
  ('Clorox Clinging Bleach Gel Ocean Mist Toilet Bowl Cleaner', 'clorox clinging bleach gel ocean mist toilet bowl cleaner', 'Household', 'Cleaning & Paper', 'HEB', ARRAY['HEB'], 2, 'per type', 1),
  ('Dawn Ultra Dishwashing Liquid Original', 'dawn ultra dishwashing liquid original', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Downy Soft, 2 in 1 Soft and Fresh Liquid Fabric Softener', 'downy soft, 2 in 1 soft and fresh liquid fabric softener', 'Household', 'Cleaning & Paper', 'Amazon', ARRAY['Amazon'], 2, 'per type', 1),
  ('Flushable Adult Toilet Wipes', 'flushable adult toilet wipes', 'Household', 'Cleaning & Paper', 'Amazon', ARRAY['Amazon'], 2, 'per type', 1),
  ('Fresh Scent Disinfecting Wipes', 'fresh scent disinfecting wipes', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Glad ForceFlex Plus Tall Kitchen Drawstring Trash Bags', 'glad forceflex plus tall kitchen drawstring trash bags', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Lemon Scent Dishwashing Liquid', 'lemon scent dishwashing liquid', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Scrubbing Bubbles Continuous Clean Drop-Ins Discs, Toilet Bowl Cleaner Tablets', 'scrubbing bubbles continuous clean drop-ins discs, toilet bowl cleaner tablets', 'Household', 'Cleaning & Paper', 'HEB', ARRAY['HEB'], 2, 'per type', 1),
  ('Strong & Absorbent Paper Towels', 'strong & absorbent paper towels', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Tall Kitchen Drawstring Trash Bags', 'tall kitchen drawstring trash bags', 'Household', 'Cleaning & Paper', 'Amazon', ARRAY['Amazon'], 2, 'per type', 1),
  ('Tide PODS Laundry Detergent, 3-in-1 Spring Meadow', 'tide pods laundry detergent, 3-in-1 spring meadow', 'Household', 'Cleaning & Paper', 'Amazon', ARRAY['Amazon'], 2, 'per type', 1),
  ('Ultra Soft Bathroom Tissue, 12 Mega Rolls', 'ultra soft bathroom tissue, 12 mega rolls', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Ultra Strong Paper Towels, 6 Double Rolls', 'ultra strong paper towels, 6 double rolls', 'Household', 'Cleaning & Paper', 'Walmart', ARRAY['Walmart'], 2, 'per type', 1),
  ('Flex Edge Beater 3Pcs for KitchenAid Mixer Attachments', 'flex edge beater 3pcs for kitchenaid mixer attachments', 'Household', 'Kitchen Tools', 'Amazon', ARRAY['Amazon'], 0, 'N/A', 0),
  ('A+Health Dual Action Acetaminophen', 'a+health dual action acetaminophen', 'Medicine Cabinet', 'OTC Medications', 'Amazon', ARRAY['Amazon'], 1, 'bottle/box', 0),
  ('Children''s Tylenol Chewables Pain+Fever Ages 2-11', 'children''s tylenol chewables pain+fever ages 2-11', 'Medicine Cabinet', 'OTC Medications', 'Amazon', ARRAY['Amazon'], 1, 'bottle/box', 0),
  ('HealthA2Z Extra Strength Pain Relief Acetaminophen', 'healtha2z extra strength pain relief acetaminophen', 'Medicine Cabinet', 'OTC Medications', 'Amazon', ARRAY['Amazon'], 1, 'bottle/box', 0),
  ('Ibuprofen Tablets', 'ibuprofen tablets', 'Medicine Cabinet', 'OTC Medications', 'Walmart', ARRAY['Walmart'], 1, 'bottle/box', 0),
  ('100% Concord Grape Juice', '100% concord grape juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('100% Juice Cranberry Blend', '100% juice cranberry blend', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('100% White Grape Juice', '100% white grape juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Bubly Cherry Sparkling Water', 'bubly cherry sparkling water', 'Pantry', 'Beverages', 'HEB', ARRAY['HEB'], 2, 'packs per type', 1),
  ('Capri Sun Fruit Punch/Strawberry Kiwi/Pacific Cooler Variety', 'capri sun fruit punch/strawberry kiwi/pacific cooler variety', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Coca-Cola Soda Pop', 'coca-cola soda pop', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Dasani Purified Water', 'dasani purified water', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Dole All Natural 100% Pineapple Juice Can', 'dole all natural 100% pineapple juice can', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Dr Pepper Soda', 'dr pepper soda', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Flavored Water Variety Pack', 'flavored water variety pack', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Gatorade Thirst Quencher Variety Pack', 'gatorade thirst quencher variety pack', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Gatorade Zero Sugar Variety Pack', 'gatorade zero sugar variety pack', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Hawaiian Punch Fruit Juicy Red Juice', 'hawaiian punch fruit juicy red juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Kool-Aid Ghoul-Aid', 'kool-aid ghoul-aid', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Lemon 100% Juice', 'lemon 100% juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Lime 100% Juice', 'lime 100% juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Mountain Dew Citrus Soda Pop', 'mountain dew citrus soda pop', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('No Added Sweeteners 100% Apple Juice', 'no added sweeteners 100% apple juice', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Ocean Spray 100% Juice Cranberry Juice Blend', 'ocean spray 100% juice cranberry juice blend', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Ocean Spray White Cranberry-Strawberry Juice Drink', 'ocean spray white cranberry-strawberry juice drink', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Purified Drinking Water', 'purified drinking water', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Simply Orange Juice Calcium', 'simply orange juice calcium', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Sprite Lemon Lime Soda Pop', 'sprite lemon lime soda pop', 'Pantry', 'Beverages', 'Walmart', ARRAY['Walmart'], 2, 'packs per type', 1),
  ('Waterloo Watermelon Sparkling Water', 'waterloo watermelon sparkling water', 'Pantry', 'Beverages', 'HEB', ARRAY['HEB'], 2, 'packs per type', 1),
  ('Ball Park Classic Hot Dog Buns', 'ball park classic hot dog buns', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Butter Croissants', 'butter croissants', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Corn Tortillas', 'corn tortillas', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Entenmann''s Glazed Pop''ems Donuts', 'entenmann''s glazed pop''ems donuts', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Everything Bagels', 'everything bagels', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Extra Thin White Sliced Bread', 'extra thin white sliced bread', 'Pantry', 'Bread & Bakery', 'HEB', ARRAY['HEB'], 3, 'loaves/packs', 1),
  ('Flour Tortilla Wraps', 'flour tortilla wraps', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Flour Tortillas', 'flour tortillas', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('French Bread', 'french bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Hamburger Buns', 'hamburger buns', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Hot Dog Buns', 'hot dog buns', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Italian Bread', 'italian bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('La Banderita Flour Tortillas Family Pack', 'la banderita flour tortillas family pack', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Mission Fajita Flour Tortillas', 'mission fajita flour tortillas', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Mission Street Tacos Flour Tortillas', 'mission street tacos flour tortillas', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Mission Super Soft Burrito Flour Tortillas', 'mission super soft burrito flour tortillas', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Mrs Baird''s Large White Bread', 'mrs baird''s large white bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Old El Paso Flour Tortilla Bowls', 'old el paso flour tortilla bowls', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Old El Paso Taco Shells Stand n Stuff', 'old el paso taco shells stand n stuff', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Round Top Small White Enriched Sliced Bread', 'round top small white enriched sliced bread', 'Pantry', 'Bread & Bakery', 'HEB', ARRAY['HEB'], 3, 'loaves/packs', 1),
  ('Sara Lee Artesano Original Bread', 'sara lee artesano original bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Texas Toast Enriched White Sliced Bread', 'texas toast enriched white sliced bread', 'Pantry', 'Bread & Bakery', 'HEB', ARRAY['HEB'], 3, 'loaves/packs', 1),
  ('Thomas'' Plain Bagels', 'thomas'' plain bagels', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Wheat Sandwich Bread', 'wheat sandwich bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('White Sandwich Bread', 'white sandwich bread', 'Pantry', 'Bread & Bakery', 'Walmart', ARRAY['Walmart'], 3, 'loaves/packs', 1),
  ('Chewy Granola Bars Variety Pack', 'chewy granola bars variety pack', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('French Vanilla Almond Granola', 'french vanilla almond granola', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Malt O Meal Quick Cooking Hot Wheat Cereal', 'malt o meal quick cooking hot wheat cereal', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Malt-O-Meal Coco Wheats Original', 'malt-o-meal coco wheats original', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Malt-O-Meal Frosted Flakes', 'malt-o-meal frosted flakes', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Nature Valley Sweet and Salty Nut Granola Bars Variety Pack, 15 Bars', 'nature valley sweet and salty nut granola bars variety pack, 15 bars', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Old Fashioned Oats', 'old fashioned oats', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Pop-Tarts Frosted Strawberry', 'pop-tarts frosted strawberry', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Quick Oats', 'quick oats', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Sunbelt Bakery Chewy Granola Bars Fudge Dipped Coconut', 'sunbelt bakery chewy granola bars fudge dipped coconut', 'Pantry', 'Breakfast & Cereal', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('ACT II Movie Theater Butter Microwave Popcorn Pantry Packs', 'act ii movie theater butter microwave popcorn pantry packs', 'Pantry', 'Canned Goods', 'HEB', ARRAY['HEB'], 3, 'cans per type', 1),
  ('Beef Broth', 'beef broth', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Black Beans', 'black beans', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Bush''s Best Chili Beans Mild', 'bush''s best chili beans mild', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Chicken Broth', 'chicken broth', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Corn Bread Muffin Mix', 'corn bread muffin mix', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Cream of Chicken Condensed Soup', 'cream of chicken condensed soup', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Cream of Mushroom Condensed Soup', 'cream of mushroom condensed soup', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Cut Green Beans', 'cut green beans', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Dark Red Kidney Beans', 'dark red kidney beans', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Diced Tomatoes', 'diced tomatoes', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Fritos Original Corn Chips', 'fritos original corn chips', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Guerrero White Corn Tostadas', 'guerrero white corn tostadas', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Hunt''s Tomato Paste', 'hunt''s tomato paste', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Jiffy Corn Muffin Mix', 'jiffy corn muffin mix', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Kellogg''s Corn Flakes Original Cereal', 'kellogg''s corn flakes original cereal', 'Pantry', 'Canned Goods', 'HEB', ARRAY['HEB'], 3, 'cans per type', 1),
  ('Mixed Vegetables', 'mixed vegetables', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Organics Tomato Paste', 'organics tomato paste', 'Pantry', 'Canned Goods', 'HEB', ARRAY['HEB'], 3, 'cans per type', 1),
  ('Original Restaurant-Style White Corn Tortilla Chips', 'original restaurant-style white corn tortilla chips', 'Pantry', 'Canned Goods', 'HEB', ARRAY['HEB'], 3, 'cans per type', 1),
  ('Pinto Beans', 'pinto beans', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('RO*TEL Original Diced Tomatoes and Green Chilies', 'ro*tel original diced tomatoes and green chilies', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Round Bite Size White Corn Tortilla Chips', 'round bite size white corn tortilla chips', 'Pantry', 'Canned Goods', 'HEB', ARRAY['HEB'], 3, 'cans per type', 1),
  ('Swanson 100% Natural Chicken Broth', 'swanson 100% natural chicken broth', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Sweet Peas', 'sweet peas', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Tomato Paste', 'tomato paste', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Tomato Sauce', 'tomato sauce', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('Whole Kernel Corn', 'whole kernel corn', 'Pantry', 'Canned Goods', 'Walmart', ARRAY['Walmart'], 3, 'cans per type', 1),
  ('100% Arabica Colombian Medium-Dark Roast Ground Coffee', '100% arabica colombian medium-dark roast ground coffee', 'Pantry', 'Coffee & Tea', 'Walmart', ARRAY['Walmart'], 2, 'bags/cans', 1),
  ('Cafe Bustelo Espresso Style Dark Roast Instant Coffee', 'cafe bustelo espresso style dark roast instant coffee', 'Pantry', 'Coffee & Tea', 'Walmart', ARRAY['Walmart'], 2, 'bags/cans', 1),
  ('Colombian Medium Dark Roast Ground Coffee', 'colombian medium dark roast ground coffee', 'Pantry', 'Coffee & Tea', 'Walmart', ARRAY['Walmart'], 2, 'bags/cans', 1),
  ('Buitoni Pesto with Basil', 'buitoni pesto with basil', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Chunky Salsa Medium', 'chunky salsa medium', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Clover Honey', 'clover honey', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Creamy Peanut Butter', 'creamy peanut butter', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Dark Chocolate Hazelnut Spread with Cocoa', 'dark chocolate hazelnut spread with cocoa', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('French Fried Onions', 'french fried onions', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Herdez Salsa Verde', 'herdez salsa verde', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Honey Nut Cheerios', 'honey nut cheerios', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Jif Creamy Peanut Butter', 'jif creamy peanut butter', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Kool-Aid Jammers Grape', 'kool-aid jammers grape', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Made in Texas Crunchy Peanut Butter - Texas Wildflower Honey', 'made in texas crunchy peanut butter - texas wildflower honey', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Medium Chunky Restaurant Style Salsa', 'medium chunky restaurant style salsa', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('More Fruit Raspberry Fruit Spread', 'more fruit raspberry fruit spread', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Nature Valley Crunchy Granola Bars Oats ''n Honey', 'nature valley crunchy granola bars oats ''n honey', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Nature''s Own Honey Wheat Bread', 'nature''s own honey wheat bread', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Nutter Butter Peanut Butter Sandwich Cookies', 'nutter butter peanut butter sandwich cookies', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Oats & Honey Granola', 'oats & honey granola', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Salsa God Medium Heat Fire Roasted Red Restaurant Style Salsa', 'salsa god medium heat fire roasted red restaurant style salsa', 'Pantry', 'Condiments & Sauces', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Tomato Ketchup', 'tomato ketchup', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Yellow Mustard', 'yellow mustard', 'Pantry', 'Condiments & Sauces', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Distilled White Vinegar', 'distilled white vinegar', 'Pantry', 'Oils & Vinegars', 'Walmart', ARRAY['Walmart'], 1, 'bottle per type', 0),
  ('PAM Original No-Stick Cooking Spray', 'pam original no-stick cooking spray', 'Pantry', 'Oils & Vinegars', 'Walmart', ARRAY['Walmart'], 1, 'bottle per type', 0),
  ('Pampers Easy Ups Training Pants', 'pampers easy ups training pants', 'Pantry', 'Oils & Vinegars', 'Amazon', ARRAY['Amazon'], 1, 'bottle per type', 0),
  ('Pure Olive Oil', 'pure olive oil', 'Pantry', 'Oils & Vinegars', 'Walmart', ARRAY['Walmart'], 1, 'bottle per type', 0),
  ('Vegetable Oil', 'vegetable oil', 'Pantry', 'Oils & Vinegars', 'Walmart', ARRAY['Walmart'], 1, 'bottle per type', 0),
  ('Barilla Classic Fettuccine Pasta', 'barilla classic fettuccine pasta', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Corkscrew Cavatappi Pasta Noodles', 'corkscrew cavatappi pasta noodles', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Enriched Macaroni Product Elbow Macaroni', 'enriched macaroni product elbow macaroni', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Enriched Spaghetti', 'enriched spaghetti', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Garlic & Herb Pasta Sauce', 'garlic & herb pasta sauce', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Kraft Original Flavor Macaroni and Cheese', 'kraft original flavor macaroni and cheese', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Kraft Original Mac & Cheese Macaroni and Cheese Dinner', 'kraft original mac & cheese macaroni and cheese dinner', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Macaroni & Cheese', 'macaroni & cheese', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Organic Bronze Cut Rigatoni', 'organic bronze cut rigatoni', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Original Mac & Cheese - Texas-Size Pack', 'original mac & cheese - texas-size pack', 'Pantry', 'Pasta & Noodles', 'HEB', ARRAY['HEB'], 4, 'boxes', 2),
  ('Penne Pasta', 'penne pasta', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Shells & Cheese', 'shells & cheese', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Velveeta Shells & Cheese Original', 'velveeta shells & cheese original', 'Pantry', 'Pasta & Noodles', 'Walmart', ARRAY['Walmart'], 4, 'boxes', 2),
  ('Jongga Spicy Stir-Fried Kimchi Ramen', 'jongga spicy stir-fried kimchi ramen', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Long Grain Enriched Rice', 'long grain enriched rice', 'Pantry', 'Rice & Grains', 'Walmart', ARRAY['Walmart'], 2, 'bags/packs', 1),
  ('Malt-O-Meal Crispy Rice Cereal', 'malt-o-meal crispy rice cereal', 'Pantry', 'Rice & Grains', 'Walmart', ARRAY['Walmart'], 2, 'bags/packs', 1),
  ('Maruchan Instant Lunch Ramen Noodle Soup - Chicken Flavor', 'maruchan instant lunch ramen noodle soup - chicken flavor', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Maruchan Ramen Noodle Soup - Chili Flavor', 'maruchan ramen noodle soup - chili flavor', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Maruchan Ramen Noodle Soup - Lime Chili Shrimp Flavor', 'maruchan ramen noodle soup - lime chili shrimp flavor', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Maruchan Ramen Noodle Soup Packs - Beef Flavor', 'maruchan ramen noodle soup packs - beef flavor', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Maruchan Ramen Noodle Soup Packs - Chicken Flavor', 'maruchan ramen noodle soup packs - chicken flavor', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Rice Krispies Treats Original', 'rice krispies treats original', 'Pantry', 'Rice & Grains', 'Walmart', ARRAY['Walmart'], 2, 'bags/packs', 1),
  ('Tapatio Spicy Chicken Ramen Noodle Soup Bowl', 'tapatio spicy chicken ramen noodle soup bowl', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Tapatio Spicy Original Ramen Noodle Soup Bowl', 'tapatio spicy original ramen noodle soup bowl', 'Pantry', 'Rice & Grains', 'HEB', ARRAY['HEB'], 2, 'bags/packs', 1),
  ('Animal Crackers', 'animal crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Bakery Tortilla Chips - Sea Salt', 'bakery tortilla chips - sea salt', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Bite Size Tortilla Chips', 'bite size tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Cheddar Lone Stars Baked Snack Crackers', 'cheddar lone stars baked snack crackers', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Cheetos Crunchy Cheese Flavored Snacks', 'cheetos crunchy cheese flavored snacks', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Cheetos Puffs Cheese Flavored Snacks', 'cheetos puffs cheese flavored snacks', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Cheez-It Original Baked Snack Crackers', 'cheez-it original baked snack crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Chips Ahoy! Original Chocolate Chip Cookies', 'chips ahoy! original chocolate chip cookies', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Doritos Cool Ranch Tortilla Chips', 'doritos cool ranch tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Doritos Nacho Cheese Tortilla Chips', 'doritos nacho cheese tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Entenmann''s Little Bites Chocolate Chip Muffins', 'entenmann''s little bites chocolate chip muffins', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Garlic Parmesan Lone Stars Baked Snack Crackers', 'garlic parmesan lone stars baked snack crackers', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Goldfish Cheddar Crackers', 'goldfish cheddar crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Hot Cheetos Flamin'' Hot Crunchy', 'hot cheetos flamin'' hot crunchy', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Lay''s Classic Potato Chips', 'lay''s classic potato chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Lay''s Sour Cream & Onion Potato Chips', 'lay''s sour cream & onion potato chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Mini Chocolate Chip Muffins', 'mini chocolate chip muffins', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Original Tortilla Chips', 'original tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Pica Puffs Chile Limon Pita Puff Crackers', 'pica puffs chile limon pita puff crackers', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Premium Original Saltine Crackers', 'premium original saltine crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Ritz Bits Cheese Sandwich Crackers Multipack', 'ritz bits cheese sandwich crackers multipack', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Ritz Original Crackers', 'ritz original crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Ruffles Cheddar & Sour Cream Potato Chips', 'ruffles cheddar & sour cream potato chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('SunChips Harvest Cheddar Whole Grain Snacks', 'sunchips harvest cheddar whole grain snacks', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Sunbelt Bakery Chewy Granola Bars Chocolate Chip', 'sunbelt bakery chewy granola bars chocolate chip', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Tostitos Original Restaurant Style Tortilla Chips', 'tostitos original restaurant style tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Tostitos Scoops Tortilla Chips', 'tostitos scoops tortilla chips', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Triscuit Original Whole Grain Wheat Crackers', 'triscuit original whole grain wheat crackers', 'Pantry', 'Snacks - Chips & Crackers', 'Walmart', ARRAY['Walmart'], 3, 'bags/boxes', 1),
  ('Wavy Potato Chips - Original, Party Size', 'wavy potato chips - original, party size', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Wavy Potato Chips - Sour Cream & Onion', 'wavy potato chips - sour cream & onion', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('White Cheddar Lone Stars Baked Snack Crackers', 'white cheddar lone stars baked snack crackers', 'Pantry', 'Snacks - Chips & Crackers', 'HEB', ARRAY['HEB'], 3, 'bags/boxes', 1),
  ('Butter Cookies Holiday Tin', 'butter cookies holiday tin', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Chocolate Sugar Wafers', 'chocolate sugar wafers', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Coconut Sugar Wafers', 'coconut sugar wafers', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Coffee Sugar Wafers', 'coffee sugar wafers', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Duplex Sandwich Cookies', 'duplex sandwich cookies', 'Pantry', 'Snacks - Cookies', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Oreo Chocolate Sandwich Cookies', 'oreo chocolate sandwich cookies', 'Pantry', 'Snacks - Cookies', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Strawberry Sugar Wafers', 'strawberry sugar wafers', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Vanilla Sugar Wafers', 'vanilla sugar wafers', 'Pantry', 'Snacks - Cookies', 'HEB', ARRAY['HEB'], 2, 'packages', 1),
  ('Vanilla Wafers', 'vanilla wafers', 'Pantry', 'Snacks - Cookies', 'Walmart', ARRAY['Walmart'], 2, 'packages', 1),
  ('Monster Energy Ultra Variety Pack, POP, Sugar Free Energy Drinks', 'monster energy ultra variety pack, pop, sugar free energy drinks', 'Pantry', 'Snacks - Other', 'Amazon', ARRAY['Amazon'], 2, 'items', 1),
  ('David Original Sunflower Seeds', 'david original sunflower seeds', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Fruit Roll-Ups Variety Pack', 'fruit roll-ups variety pack', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Fruit Snack', 'fruit snack', 'Pantry', 'Snacks - Sweet & Other', 'HEB', ARRAY['HEB'], 3, 'boxes/bags', 1),
  ('Gimme Seaweed Organic Premium Roasted Seaweed Snacks, Sea Salt', 'gimme seaweed organic premium roasted seaweed snacks, sea salt', 'Pantry', 'Snacks - Sweet & Other', 'Amazon', ARRAY['Amazon'], 3, 'boxes/bags', 1),
  ('Gushers Tropical and Strawberry Variety', 'gushers tropical and strawberry variety', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Hershey''s Milk Chocolate Snack Size Bars', 'hershey''s milk chocolate snack size bars', 'Pantry', 'Snacks - Sweet & Other', 'HEB', ARRAY['HEB'], 3, 'boxes/bags', 1),
  ('Hershey''s Special Dark Mildly Sweet Chocolate Giant Candy Bar', 'hershey''s special dark mildly sweet chocolate giant candy bar', 'Pantry', 'Snacks - Sweet & Other', 'HEB', ARRAY['HEB'], 3, 'boxes/bags', 1),
  ('Little Debbie Cosmic Brownies', 'little debbie cosmic brownies', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Little Debbie Oatmeal Creme Pies', 'little debbie oatmeal creme pies', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Slim Jim 6g Protein Original Snack-Size Smoked Meat Sticks Pantry Pack', 'slim jim 6g protein original snack-size smoked meat sticks pantry pack', 'Pantry', 'Snacks - Sweet & Other', 'HEB', ARRAY['HEB'], 3, 'boxes/bags', 1),
  ('Slim Jim Original Smoked Snack Stick', 'slim jim original smoked snack stick', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Trail Mix', 'trail mix', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('Welch''s Fruit Snacks Mixed Fruit', 'welch''s fruit snacks mixed fruit', 'Pantry', 'Snacks - Sweet & Other', 'Walmart', ARRAY['Walmart'], 3, 'boxes/bags', 1),
  ('gimme Roasted Seaweed Snacks - Sea Salt', 'gimme roasted seaweed snacks - sea salt', 'Pantry', 'Snacks - Sweet & Other', 'HEB', ARRAY['HEB'], 3, 'boxes/bags', 1),
  ('2-Ply Soft Toilet Paper', '2-ply soft toilet paper', 'Personal Care', 'Bathroom', 'Amazon', ARRAY['Amazon'], 1, 'per type', 0),
  ('Alberto VO5 Moisturizing Shampoo - Pomegranate Bliss', 'alberto vo5 moisturizing shampoo - pomegranate bliss', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Alberto VO5 Pomegranate Bliss Moisturizing Conditioner', 'alberto vo5 pomegranate bliss moisturizing conditioner', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Colgate Total Whitening Toothpaste', 'colgate total whitening toothpaste', 'Personal Care', 'Bathroom', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Degree Men Original Antiperspirant Deodorant Cool Rush', 'degree men original antiperspirant deodorant cool rush', 'Personal Care', 'Bathroom', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Dove Beauty Bar White', 'dove beauty bar white', 'Personal Care', 'Bathroom', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Hi Pro Pac Keratin Protein No-Frizz Hair Intense Protein Treatment', 'hi pro pac keratin protein no-frizz hair intense protein treatment', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Hi Pro Pac Moroccan Mend Argan Oil Deep Repair Masque', 'hi pro pac moroccan mend argan oil deep repair masque', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Kristin Ess Moisture Rich Curl Conditioner', 'kristin ess moisture rich curl conditioner', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Native Brightening Facial Cleanser - Citrus & Bergamot', 'native brightening facial cleanser - citrus & bergamot', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Native Lotion - Eucalyptus & Mint', 'native lotion - eucalyptus & mint', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Native Volumizing Conditioner - Cucumber & Mint', 'native volumizing conditioner - cucumber & mint', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Spider-Man Berry Blast 3-in-1 Body Wash, Shampoo and Conditioner', 'spider-man berry blast 3-in-1 body wash, shampoo and conditioner', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Suave Essentials Conditioner Ocean Breeze', 'suave essentials conditioner ocean breeze', 'Personal Care', 'Bathroom', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Suave Essentials Shampoo Ocean Breeze', 'suave essentials shampoo ocean breeze', 'Personal Care', 'Bathroom', 'Walmart', ARRAY['Walmart'], 1, 'per type', 0),
  ('Suave Men Refreshing 2-in-1 Face & Body Wash - Cedarwood & Mandarin', 'suave men refreshing 2-in-1 face & body wash - cedarwood & mandarin', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Suave Uplifting Body Wash - Sweet Pea & Violet', 'suave uplifting body wash - sweet pea & violet', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('VO5 Blooming Freesia Moisturizing Conditioner', 'vo5 blooming freesia moisturizing conditioner', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('VO5 Blooming Freesia Moisturizing Shampoo', 'vo5 blooming freesia moisturizing shampoo', 'Personal Care', 'Bathroom', 'HEB', ARRAY['HEB'], 1, 'per type', 0),
  ('Petite Diced Tomatoes', 'petite diced tomatoes', 'Pets', 'Pet Supplies', 'Walmart', ARRAY['Walmart'], 1, 'item', 0),
  ('Texas Pets Tough ''N'' Stuffed Dog Chew - Chicken, Each', 'texas pets tough ''n'' stuffed dog chew - chicken, each', 'Pets', 'Pet Supplies', 'HEB', ARRAY['HEB'], 1, 'item', 0),
  ('Goya Sazon Seasoning', 'goya sazon seasoning', 'Spice Cabinet', 'Spices & Seasonings', 'Walmart', ARRAY['Walmart'], 1, 'container', 0),
  ('Dannon DanActive Strawberry Probiotic Drink', 'dannon danactive strawberry probiotic drink', 'Supplements', 'Daily Supplements', 'Walmart', ARRAY['Walmart'], 1, 'bottle', 0),
  ('Futurebiotics Ashwagandha Extra Strength Stress & Mood Support with BioPerine', 'futurebiotics ashwagandha extra strength stress & mood support with bioperine', 'Supplements', 'Daily Supplements', 'Amazon', ARRAY['Amazon'], 1, 'bottle', 0),
  ('Liquid I.V. Hydration Multiplier - Concord Grape Electrolyte Powder', 'liquid i.v. hydration multiplier - concord grape electrolyte powder', 'Supplements', 'Daily Supplements', 'Amazon', ARRAY['Amazon'], 1, 'bottle', 0),
  ('NatureGenX Vitamin D3 Liquid Drops - Immune Support & Bone Health', 'naturegenx vitamin d3 liquid drops - immune support & bone health', 'Supplements', 'Daily Supplements', 'Amazon', ARRAY['Amazon'], 1, 'bottle', 0),
  ('Opti-Meal Cafeccino 10g Protein Shakes', 'opti-meal cafeccino 10g protein shakes', 'Supplements', 'Daily Supplements', 'HEB', ARRAY['HEB'], 1, 'bottle', 0),
  ('Whole Vitamin D Milk, Gallon', 'whole vitamin d milk, gallon', 'Supplements', 'Daily Supplements', 'Walmart', ARRAY['Walmart'], 1, 'bottle', 0),
  ('Whole Vitamin D Milk, Half Gallon', 'whole vitamin d milk, half gallon', 'Supplements', 'Daily Supplements', 'Walmart', ARRAY['Walmart'], 1, 'bottle', 0);